FROM alpine:latest

RUN apk add --no-cache curl wget

RUN wget https://github.com/oliver006/redis_exporter/releases/download/v1.74.0/redis_exporter-v1.74.0.linux-amd64.tar.gz \
    && tar -xzf redis_exporter-v1.74.0.linux-amd64.tar.gz \
    && mv redis_exporter-v1.74.0.linux-amd64/redis_exporter /bin/redis_exporter \
    && rm -rf redis_exporter-v1.74.0.linux-amd64*

EXPOSE 9121
ENTRYPOINT ["/bin/redis_exporter"]