FROM debian:stable-slim

RUN apt-get update && apt-get install -y curl wget unzip

RUN wget https://github.com/grafana/loki/releases/download/v2.9.2/promtail-linux-amd64.zip \
    && unzip promtail-linux-amd64.zip \
    && chmod +x promtail-linux-amd64 \
    && mv promtail-linux-amd64 /usr/bin/promtail \
    && rm promtail-linux-amd64.zip

EXPOSE 9080
ENTRYPOINT ["/usr/bin/promtail"]